# Generated by Django 2.0 on 2018-01-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171111_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleko', models.CharField(max_length=100)),
                ('titleen', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentko', models.TextField()),
                ('contenten', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='demoresource',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='member',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='report',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='github',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
    ]
