# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180304_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='title',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='writer',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='career',
            new_name='research_on',
        ),
        migrations.RenameField(
            model_name='relatedproject',
            old_name='writer',
            new_name='Institutions',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='date',
        ),
        migrations.RemoveField(
            model_name='relatedproject',
            name='content',
        ),
        migrations.RemoveField(
            model_name='relatedproject',
            name='date',
        ),
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='Authors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='Publication',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='Sourcecode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
