# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180304_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedproject',
            old_name='Publication',
            new_name='Publication_link',
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='Publication_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='image',
            field=models.ImageField(upload_to='RelatedProject/'),
        ),
    ]
