# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180304_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('Writer', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image_raw', models.ImageField(upload_to='AutomaticNews/')),
                ('image_prediction', models.ImageField(upload_to='AutomaticNews/')),
                ('report', models.FileField(upload_to='RelatedProject/')),
                ('submenu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu')),
            ],
        ),
    ]
