# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_automaticnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticnews',
            name='date',
            field=models.TimeField(),
        ),
    ]
