# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180304_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticnews',
            name='date',
        ),
        migrations.AddField(
            model_name='automaticnews',
            name='datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
