# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180304_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automaticnews',
            old_name='image_prediction',
            new_name='image_predic',
        ),
    ]
