# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20180304_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticnews',
            name='submenu_id',
        ),
        migrations.DeleteModel(
            name='AutomaticNews',
        ),
    ]
