# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_automaticnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticnews',
            name='image_prediect',
            field=models.ImageField(upload_to='AutomaticNews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='automaticnews',
            name='image_raw',
            field=models.ImageField(upload_to='AutomaticNews/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='automaticnews',
            name='report_pdf',
            field=models.FileField(upload_to='AutomaticNews/%Y/%m/%d'),
        ),
    ]
