# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20180304_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticnews',
            name='image',
        ),
    ]
