# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_automaticnews_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automaticnews',
            old_name='image_prediect',
            new_name='image_predict',
        ),
    ]
