# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20180304_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturenote',
            name='submenu_id',
        ),
        migrations.RemoveField(
            model_name='lecturevideo',
            name='submenu_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='submenu_id',
        ),
        migrations.DeleteModel(
            name='LectureNote',
        ),
        migrations.DeleteModel(
            name='LectureVideo',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
