# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_automaticnews2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomaticNews',
            new_name='AutoNews',
        ),
        migrations.RemoveField(
            model_name='automaticnews2',
            name='submenu_id',
        ),
        migrations.DeleteModel(
            name='AutomaticNews2',
        ),
    ]
