# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20180304_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonews',
            name='writer',
            field=models.CharField(default='설명가능인공지능', max_length=50),
        ),
    ]
